Repository opensourcediversity/opensourcediversity.org, pull requests merged in 2021-05, with the labels that each got.

#119 Add Gitpod.io configuration
  .gitpod.yml
  README.md
  img/gitpod.png
Labels: enhancement

#114 Use 2-column-layout on medium-small screens as intermediate step
  css/custom.css
  index.html
Labels: enhancement

#100 Fix typo in 'Diversify Open Source Bangalore' on main page
  index.html
Labels: bug

#122 ci: Use tidy to catch HTML errors in CI (closes #120)
  .circleci/config.yml
  .circleci/deploy.sh
  .gitlab-ci.yml
Labels: new change, quality assurance
